### PR TITLE
Louvain modularity

### PR DESCRIPTION
**Pull request by tpoisot**

### CODE REVIEW

**Comment by jingpengw** [comment]
is this function got removed in the master branch?

**Comment by tpoisot** [comment]
For the moment, yes -- it might be added back into `develop` (if you want to make a pull request to try, that would be helpful!).

**Comment by jingpengw** [comment]
is the label propagation algorithm better than louvain?

**Comment by tpoisot** [comment]
@jingpengw I think it depends -- for large bipartite graphs, probably.

**Pull request merged**
